# Generated by Django 5.2.5 on 2026-04-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_league_event_league_leaguemembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguemembership',
            name='league',
        ),
        migrations.RemoveField(
            model_name='event',
            name='league',
        ),
        migrations.AlterUniqueTogether(
            name='leaguemembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leaguemembership',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(choices=[('default', 'Glitch Mafia (Green)'), ('dhurandhar', 'Dhurandhar (Gold/Grit)')], default='default', max_length=20),
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='LeagueMembership',
        ),
    ]
