# Generated by Django 5.2.5 on 2026-04-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_remove_leaguemembership_league_remove_event_league_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='theme',
        ),
    ]
