# Generated by Django 5.2.5 on 2026-04-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_remove_event_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide event from non-registered users'),
        ),
    ]
