# Generated by Django 5.2.5 on 2026-04-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_event_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='challenges_locked',
            field=models.BooleanField(default=False, help_text='Lock all challenges, making them invisible to participants'),
        ),
    ]
