# Generated by Django 5.2.5 on 2026-04-28 20:26

import administration.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_event_challenges_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(administration.models.get_default_superuser), to=settings.AUTH_USER_MODEL),
        ),
    ]
