# Generated by Django 5.2.5 on 2026-04-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventaccess',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
