# Generated by Django 5.2.5 on 2026-04-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_eventaccess_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventaccess',
            name='last_active',
        ),
    ]
