# Generated by Django 5.2.5 on 2026-03-31 14:58

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_announcement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeattachment',
            name='file',
            field=models.FileField(upload_to=challenges.models.challenge_attachment_upload_path),
        ),
    ]
