# Generated by Django 5.2.5 on 2026-04-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_alter_challengeattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='FaFlag', help_text='React icon name (e.g., FaGlobe, FaBug)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(default='misc', max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges_new', to='challenges.category'),
        ),
    ]
