# Generated by Django 5.2.5 on 2026-04-23 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_category_alter_challenge_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='category_new',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='challenges.category'),
        ),
    ]
