# Generated by Django 5.2.5 on 2026-04-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_cleanup_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('crypto', 'Crypto'), ('osint', 'OSINT'), ('pwn', 'Pwn'), ('forensics', 'Forensics'), ('misc', 'Misc')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
