# Generated by Django 5.2.5 on 2026-04-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_alter_challenge_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('web', 'Web Exploitation'), ('crypto', 'Cryptography'), ('osint', 'OSINT'), ('pwn', 'Binary Exploitation (Pwn)'), ('forensics', 'Digital Forensics'), ('re', 'Reverse Engineering'), ('mobile', 'Mobile Security'), ('hardware', 'Hardware / IoT'), ('stego', 'Steganography'), ('misc', 'Miscellaneous')], max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('insane', 'Insane')], max_length=10),
        ),
    ]
